# Basic
name:               "Rahul Kondi"

# URL
baseurl:            ""
#baseurl:            "" #For Root Domain
permalink:          /:title

# Markdown
markdown:           rdiscount

# Navigation
nav:
  - name:           "/ About"
    href:           "/about/"
  - name:           "/ Contact"
    href:           "/contact/"

# Sass
sass:
  style:            :compressed

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"
