# Basic
name:               "History Maker"

# URL
baseurl:            "http://rahulkondi.github.io/"
#baseurl:            "" #For Root Domain
permalink:          /:title

# Markdown
markdown:           rdiscount

# Navigation
nav:
  - name:           "/history_maker"
    href:           "/about/"
  - name:           "/rahul_kondi"
    href:           "/contact/"

# Sass
sass:
  style:            :compressed

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"
